config/routes.rb
Rails.application.routes.draw do
  get 'chat/index'
  get 'products/index'

  get 'products/show'

  get '/books', to: 'books#index'
  post 'books_upload', to: 'books#upload'

  get 'books_download', to: 'books#download'



  devise_for :users
  resources :taggings
  resources :tags, except: :show
  resources :books
  resources :line_items, only:[:index, :show, :new, :create, :destroy] do
    collection do
      post :confirm
    end
  end

  resources :products
  resources :orders, only:[:index, :show, :new, :create] do
    collection do
      post :confirm
    end
  end

  resources :order_details
  resources :carts

  root 'products#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  devise_scope :user do
    get '/user/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'mypage#index'
  get :mypage, to: 'mypage#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    attr_accessor :csv_file
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings
    has_many :line_items
    has_many :order_details
    has_many :carts, dependent: :destroy

    has_attached_file :picture
    validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

    validates :title, presence: true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :books, through: :line_items

    #商品を検索
    #カートに同じ本があればそのIDを取得し、同じ本がなければ新規作成の対象となる
    def add_book(book_id)
        line_items.find_or_initialize_by(book_id: book_id)
    end

    #カート全体の合計金額
    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end

    #カート全体の商品数
    def total_number
        line_items.to_a.sum { |item| item.quantity }
    end

end

app/models/check_item.rb
class CheckItem < ApplicationRecord
  belongs_to :book
  belongs_to :favorite
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    #Favoritesの削除時は、favorite_idに紐づくcheck_itemsのデータも削除される
    has_many :check_items, dependent: :destroy

    #favoriteモデルにcheck_itemを登録するメソッド
    #商品が既にあれば取得、なければ新規でcheck_itemオブジェクトを生成し、check_itemオブジェクトを返す
    def add_product(product_id)
        check_items.find_or_initialize_by(product_id: product_id)
    end


end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :book
  belongs_to :cart

  #商品ごとの合計金額を出す
  def total_price
    book.price * quantity
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :book, optional: true
  has_many :order_details, dependent: :destroy
  has_many :line_items

  enum status: {resistered: 0, payed: 1, delivered: 2}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :book
  belongs_to :order

  #購入処理時にカート情報を引き継ぐ
  def self.create_items(order, line_items)
    line_items.each do |item|
      OrderDetail.create!(
        order_id: order.id, book_id: item.book_id, quantity: item.quantity
      )
      LineItem.find(item.id).delete
    end
  end

  def total_price
    book.price * quantity
  end
  
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :check_items
    has_many :books
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings, dependent: :destroy
    has_many :books, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :recoverable, :rememberable,
  devise :database_authenticatable, :registerable, 
		:trackable, :validatable
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_url, notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tags_url, notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
    def current_favorite?(book, favorite)
        favorite.check_items.map{|i| i.book_id}.include?(book.id)
    end
    
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
    def current_favorite?(product, favorite)
        favorite.check_items.map{|i|i.product_id}.include?(product.id)
    end
    
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<!doctype html>
<html lang="ja" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>カバー for Bootstrap · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/cover/">

    

    <!-- Bootstrap core CSS -->
<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">

<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
</head>
<body class="d-flex h-100 text-center text-white bg-dark">

<header>
      <ul><br>
        <div align="right">
          <a><%= link_to 'TOP', products_index_path %></a>
        </div>
      </ul>
</header>

<p id="notice"><%= notice %></p>


<%= form_with(model: [@books, @line_item], local: true, url: orders_back_path, method: :post) do |form| %>

<p>
  <strong>商品:</strong>
  <%= @line_item.book_id %>
  <%= @books.title %>
</p>

<% end %>

<p class="agw_dt_buy-button">
    <%= link_to 'カート一覧', line_items_path, html_options = {class: "btn btn-lg btn-warning"} %>

</p>