config/routes.rb
Rails.application.routes.draw do
  get 'chat/index'
  get 'products/index'

  get 'products/show'

  get '/books', to: 'books#index'
  post 'books_upload', to: 'books#upload'

  get 'books_download', to: 'books#download'



  devise_for :users
  resources :taggings
  resources :tags, except: :show
  resources :books
  resources :line_items, only:[:index, :show, :new, :create, :destroy] do
    collection do
      post :confirm
    end
  end

  resources :products
  resources :orders, only:[:index, :show, :new, :create] do
    collection do
      post :confirm
    end
  end

  resources :order_details
  resources :carts

  root 'products#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  devise_scope :user do
    get '/user/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'mypage#index'
  get :mypage, to: 'mypage#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    attr_accessor :csv_file
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings
    has_many :line_items
    has_many :order_details
    has_many :carts, dependent: :destroy

    has_attached_file :picture
    validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

    validates :title, presence: true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :books, through: :line_items

    #商品を検索
    #カートに同じ本があればそのIDを取得し、同じ本がなければ新規作成の対象となる
    def add_book(book_id)
        line_items.find_or_initialize_by(book_id: book_id)
    end

    #カート全体の合計金額
    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end

    #カート全体の商品数
    def total_number
        line_items.to_a.sum { |item| item.quantity }
    end

end

app/models/check_item.rb
class CheckItem < ApplicationRecord
  belongs_to :book
  belongs_to :favorite
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    #Favoritesの削除時は、favorite_idに紐づくcheck_itemsのデータも削除される
    has_many :check_items, dependent: :destroy

    #favoriteモデルにcheck_itemを登録するメソッド
    #商品が既にあれば取得、なければ新規でcheck_itemオブジェクトを生成し、check_itemオブジェクトを返す
    def add_product(product_id)
        check_items.find_or_initialize_by(product_id: product_id)
    end


end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :book
  belongs_to :cart

  #商品ごとの合計金額を出す
  def total_price
    book.price * quantity
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :book, optional: true
  has_many :order_details, dependent: :destroy
  has_many :line_items

  enum status: {resistered: 0, payed: 1, delivered: 2}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :book
  belongs_to :order

  #購入処理時にカート情報を引き継ぐ
  def self.create_items(order, line_items)
    line_items.each do |item|
      OrderDetail.create!(
        order_id: order.id, book_id: item.book_id, quantity: item.quantity
      )
      LineItem.find(item.id).delete
    end
  end

  def total_price
    book.price * quantity
  end
  
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :check_items
    has_many :books
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings, dependent: :destroy
    has_many :books, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :recoverable, :rememberable,
  devise :database_authenticatable, :registerable, 
		:trackable, :validatable
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!

  #indexアクション(商品であるBookの一覧)
  def index
    @q = Book.ransack params[:q]
    @products = @q.result
    #@products = Book.all
  end

  #showアクション(Book1冊の詳細)
  def show
    @product = Book.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
    def current_favorite?(book, favorite)
        favorite.check_items.map{|i| i.book_id}.include?(book.id)
    end
    
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
    def current_favorite?(product, favorite)
        favorite.check_items.map{|i|i.product_id}.include?(product.id)
    end
    
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_sidebar.html.erb
<div class="col-12 col-md-3 sidebar-offcanvas" id="sidebar">
  <h2 class="side-ttl">カテゴリから探す</h2>
  <ul class="list-group agw_side-list">
    <% @tags.each do |tag| %>
      <li class="list-group-item"><%= tag.name %></li>
    <% end %>
  </ul>

</div><!--/span-->

app/views/products/index.html.erb
<!doctype html>
<html lang="ja" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>カバー for Bootstrap · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/cover/">

    

    <!-- Bootstrap core CSS -->
<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">

<style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">
    
<div class="menu">

<header>
      <ul><br>
        <div align="right">
          <p>こんにちは、<%= current_user.email %>さん</p><br>
          <a><%= link_to '買い物かご', line_items_path(cart_id: @current_cart) %></a>
          <a><%= link_to 'カート一覧', carts_path %></a>
          <a><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></a>
        </div>
      </ul>
</header>

</div>

<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

  <header class="mb-auto">
    <div>
      <h1 class="text-center">商品一覧</h1>
    </div>
<br> 

<div style="padding: 10px; margin-bottom: 10px; border: 5px double #034149;">
      <h5 class="text-center">絞り込み検索</h5><br>
      <%= search_form_for @q, url: products_index_path, method: :get do |f| %>
        <div align="center">
        <table>
          <tr>
            <th>タイトル or 著者</th>
            <td><%= f.text_field :title_or_author_cont %></td>
          <tr>
          <tr>
            <th>出版日</th>
            <td><%= f.date_field :published_on_gteq %>～<%= f.date_field :published_on_lteq %></td>
          </tr>
          <tr>
            <th>価格</th>
            <td><%= f.text_field :price_gteq %> 円 ～ <%= f.text_field :price_lteq %> 円</td>
          </tr>
        </table>
        </div>
        <div align="right">
          <button class="btn btn-outline-success" type="submit"><%= f.submit 'Search' %></button>
        </div>
      <% end %>
    </div> 



<table class="table table-dark table-striped">
  <thread>
    <tr>
      <th>タイトル</th>
      <th>著者</th>
      <th>出版日</th>
      <th>価格</th>
    </tr>
  </thread>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.title, product_path(product) %>
        <td><%= product.author %>
        <td><%= product.published_on %>
        <td><%= number_to_currency(product.try(:price), precision: 0, unit: "円") %>
      </tr>
    <% end %>
  </tbody>
</table>
</body>

app/views/products/show.html.erb
<!doctype html>
<html lang="ja" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>カバー for Bootstrap · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/cover/">

    

    <!-- Bootstrap core CSS -->
<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">

<style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">

  

  <div>
      <br>
      <h3><%= @product.title %></h3><br>
      <p class="agw_dt_date">出版：<%= @product.published_on %></p>
      <p class="agw_dt_author">著者：<%= @product.author %></p>
      <p class="agw_dt_price">価格：<%= number_to_currency @product.price, precision: 0, unit: "", format: "%u %n" %><span>円</span></p>
      <%= image_tag @product.picture.url, width: 300  if @product.picture.present? %><br>
      <br>


      <br>

      <p class="agw_dt_buy-button">
        <%= link_to 'カートに入れる', new_line_item_path(book_id: @product.id), html_options = {class: "btn btn-light"} %>
        <%= link_to '戻る', products_path, html_options = {class: "btn btn-light"} %>
        </p>
    </div>