config/routes.rb
Rails.application.routes.draw do
  get 'chat/index'
  get 'products/index'

  get 'products/show'

  get '/books', to: 'books#index'
  post 'books_upload', to: 'books#upload'

  get 'books_download', to: 'books#download'



  devise_for :users
  resources :taggings
  resources :tags, except: :show
  resources :books
  resources :line_items, only:[:index, :show, :new, :create, :destroy] do
    collection do
      post :confirm
    end
  end

  resources :products
  resources :orders, only:[:index, :show, :new, :create] do
    collection do
      post :confirm
    end
  end

  resources :order_details
  resources :carts

  root 'products#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  devise_scope :user do
    get '/user/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'mypage#index'
  get :mypage, to: 'mypage#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    attr_accessor :csv_file
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings
    has_many :line_items
    has_many :order_details
    has_many :carts, dependent: :destroy

    has_attached_file :picture
    validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

    validates :title, presence: true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :books, through: :line_items

    #商品を検索
    #カートに同じ本があればそのIDを取得し、同じ本がなければ新規作成の対象となる
    def add_book(book_id)
        line_items.find_or_initialize_by(book_id: book_id)
    end

    #カート全体の合計金額
    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end

    #カート全体の商品数
    def total_number
        line_items.to_a.sum { |item| item.quantity }
    end

end

app/models/check_item.rb
class CheckItem < ApplicationRecord
  belongs_to :book
  belongs_to :favorite
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    #Favoritesの削除時は、favorite_idに紐づくcheck_itemsのデータも削除される
    has_many :check_items, dependent: :destroy

    #favoriteモデルにcheck_itemを登録するメソッド
    #商品が既にあれば取得、なければ新規でcheck_itemオブジェクトを生成し、check_itemオブジェクトを返す
    def add_product(product_id)
        check_items.find_or_initialize_by(product_id: product_id)
    end


end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :book
  belongs_to :cart

  #商品ごとの合計金額を出す
  def total_price
    book.price * quantity
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :book, optional: true
  has_many :order_details, dependent: :destroy
  has_many :line_items

  enum status: {resistered: 0, payed: 1, delivered: 2}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :book
  belongs_to :order

  #購入処理時にカート情報を引き継ぐ
  def self.create_items(order, line_items)
    line_items.each do |item|
      OrderDetail.create!(
        order_id: order.id, book_id: item.book_id, quantity: item.quantity
      )
      LineItem.find(item.id).delete
    end
  end

  def total_price
    book.price * quantity
  end
  
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :check_items
    has_many :books
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings, dependent: :destroy
    has_many :books, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :recoverable, :rememberable,
  devise :database_authenticatable, :registerable, 
		:trackable, :validatable
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: %i[ show edit update destroy ]

  # GET /line_items or /line_items.json
  #セッションごとのカートの商品を全件表示
  def index
    #@line_items = LineItem.all
    @line_items = LineItem.where(cart_id: @current_cart)
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @product = Book.find(params[:book_id].to_i)
    @line_item = LineItem.new
  end

  def confirm
    @product = Book.find(line_item_params[:book_id])
    @line_item = LineItem.new(line_item_params)
  end




  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  #カートに紐づく注文情報を登録する
  def create
    #セッション情報(カート情報の取得)
    cart = current_cart
    #注文された商品の情報を取得
    book = Book.where(id: params[:book_id])
    #add_bookで既にカートにあるものかどうかを判断する
    #@line_itemにカートIDとbookIDが渡る
    @line_item = cart.add_book(book)

    @line_item = LineItem.new(line_item_params)


        if @line_item.save
          flash[:notice] = "買い物かごに追加しました。"
          redirect_to products_index_path

    # @line_items = LineItem.all
    # @line_items.each do |line_item|
    #   if line_item.book_id == @line_item.book_id && current_cart
    #     new_quantity = line_item.quantity + @line_item.quantity
    #     line_item.update_attribute(:quantity, new_quantity)
    #     @line_item.delete
    #   end 
    # end
        else
          flash[:notice] = "買い物かごに追加できませんでした。"
          redirect_to products_index_path
        end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: "カートから商品が削除されました" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:book_id, :cart_id, :quantity)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
    def current_favorite?(book, favorite)
        favorite.check_items.map{|i| i.book_id}.include?(book.id)
    end
    
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
    def current_favorite?(product, favorite)
        favorite.check_items.map{|i|i.product_id}.include?(product.id)
    end
    
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.text_field :book_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/confirm.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>申し込みフォームサンプル for Bootstrap · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/checkout/">

    

    <!-- Bootstrap core CSS -->
<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <!-- Custom styles for this template -->
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">

  <div class="container">
  <main>
    <div>
      <h2>カートに追加する商品</h2><br>
      <h5 class="agw_dt_book-ttl"><%= @product.title %></h5>
      <p class="agw_dt_plice2"><%= @product.author %></p>
      <p class="agw_dt_plice2"><%= number_to_currency @product.price, precision: 0, unit: "", format: "%u %n" %><span>円 （税込）</span></p>
    </div>
  </div>
<br>

<div class="col-12 col-md-3 sidebar-offcanvas" id="sidebar">
  <div class="agw_side-cart_block">

  <div class="text-center">
    <%= form_with(model: @line_item, local: true) do |form| %>
      <ul class="agw_side-cart_block_inner">
      <div class="text-center">
        <label for="colFormLabelSm" class="buy_ttl"><%= form.label :数量 %></label>
        <label for="colFormLabelSm" class="buy_accounts"><strong><%= @line_item.quantity %>冊</strong></label>
        <div class="col-sm-10">
          <input type="hidden" class="form-control form-control-sm">
        </div>
      </div>
      
      <div class="text-center">
        <label for="colFormLabelSm" class="buy_ttl"><%= form.label :商品合計 %></label>
        <label for="colFormLabelSm" class="buy_accounts"><strong><%= number_to_currency @product.price * @line_item.quantity, precision: 0, unit: "", format: "%u %n" %>円</strong></label>
        <div class="col-sm-10">
          <input type="hidden" class="form-control form-control-sm">
        </div>
      </div>

      <div class="text-center">
        <label for="colFormLabelSm" class="buy_ttl"><%= form.label :総合計 %></label>
        <label for="colFormLabelSm" class="buy_accounts"><strong><%= number_to_currency @product.price * @line_item.quantity, precision: 0, unit: "", format: "%u %n" %>円</strong></label>
        <div class="col-sm-10">
          <input type="hidden" class="form-control form-control-sm">
        </div>
      </div>

      </ul>

      <%= form.hidden_field :quantity, value: @line_item.quantity %>
      <%= form.hidden_field :book_id, value: @line_item.book_id %>
      <%= form.hidden_field :cart_id, value: @current_cart.id %>
      <%= form.submit "カートに入れる", class:"btn btn-danger btn-lg btn-block" %><br>

    <% end %>
    </div>
  </div>
</div>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<!doctype html>
<html lang="ja" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>カバー for Bootstrap · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/cover/">

    

    <!-- Bootstrap core CSS -->
<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">

<style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">


<p id="notice"><%= notice %></p>

<header>
      <ul><br>
        <div align="right">
          <a><%= link_to 'TOP', products_index_path %></a>
        </div>
      </ul>
</header>


<div align="left">
<h1>カートに追加された商品</h1>
</div>

<%= form_with(model: @line_item, local: true) do |form| %>

<table>
  <thead>
    <tr>
      <th>商品名</th>
      <th>数量</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.book.title %></td>
        <td><%= line_item.quantity %></td>
        <td><%= link_to '削除', line_item, method: :delete, data: { confirm: 'カートから削除してもよろしいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= form.hidden_field :cart_id, value: @current_cart %>

<% end %>

<br>



<%= link_to '購入する', cart_path(@current_cart), html_options = {class: "btn btn-lg btn-warning"} %>

app/views/line_items/new.html.erb
<!doctype html>
<html lang="ja" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>カバー for Bootstrap · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/cover/">

    

    <!-- Bootstrap core CSS -->
<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">

<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
        font-size: 3.5rem;
        }
    }
    </style>
    <!-- Custom styles for this template -->
</head>
<body class="d-flex h-100 text-center text-white bg-dark">

<%= form_with model: @line_item, local: true, url: confirm_line_items_path do |form| %>

<div>
    <p>カートに入れる数量を選択してください</p>
    <br>
    <div class="field">
        <%= form.label :数量 %>
        <%= form.number_field :quantity, {value: 1} %>
    </div>

    <%= form.hidden_field :book_id, value: @product.id %>
    <%= form.hidden_field :cart_id, value: @current_cart.id %>



    <p class="agw_dt_buy-button">
        <%= form.submit '確認', html_options = {class: "btn btn-light"} %>
        <%= link_to '戻る', products_path, html_options = {class: "btn btn-light"} %>
        </p>
    </div>

    <% end %>

app/views/line_items/show.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>申し込みフォームサンプル for Bootstrap · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/checkout/">

    

    <!-- Bootstrap core CSS -->
<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <!-- Custom styles for this template -->
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">

  <div class="container">
  <main>
    <div>
      <h2>カートに追加する商品</h2><br>
      <h5 class="agw_dt_book-ttl"><%= @product.title %></h5>
      <p class="agw_dt_plice2"><%= @product.author %></p>
      <p class="agw_dt_plice2"><%= number_to_currency @product.price, precision: 0, unit: "", format: "%u %n" %><span>円 （税込）</span></p>
    </div>
  </div>
<br>

<div class="col-12 col-md-3 sidebar-offcanvas" id="sidebar">
  <div class="agw_side-cart_block">

  <div class="text-center">
    <%= form_with(model: @line_item, local: true) do |form| %>
      <ul class="agw_side-cart_block_inner">
      <div class="text-center">
        <label for="colFormLabelSm" class="buy_ttl"><%= form.label :数量 %></label>
        <label for="colFormLabelSm" class="buy_accounts"><strong><%= @line_item.quantity %>冊</strong></label>
        <div class="col-sm-10">
          <input type="hidden" class="form-control form-control-sm">
        </div>
      </div>
      
      <div class="text-center">
        <label for="colFormLabelSm" class="buy_ttl"><%= form.label :商品合計 %></label>
        <label for="colFormLabelSm" class="buy_accounts"><strong><%= number_to_currency @product.price * @order.quantity, precision: 0, unit: "", format: "%u %n" %>円</strong></label>
        <div class="col-sm-10">
          <input type="hidden" class="form-control form-control-sm">
        </div>
      </div>

      <div class="text-center">
        <label for="colFormLabelSm" class="buy_ttl"><%= form.label :総合計 %></label>
        <label for="colFormLabelSm" class="buy_accounts"><strong><%= number_to_currency @product.price * @order.quantity, precision: 0, unit: "", format: "%u %n" %>円</strong></label>
        <div class="col-sm-10">
          <input type="hidden" class="form-control form-control-sm">
        </div>
      </div>

      </ul>

      <%= form.hidden_field :quantity, value: @line_item.quantity %>
      <%= form.hidden_field :address, value: @line_item.address %>
      <%= form.hidden_field :book_id, value: @line_item.book_id %>
      <%= form.hidden_field :user_id, value: @line_item.cart_id %>
      <%= form.submit "カートに入れる", class:"btn btn-danger btn-lg btn-block" %><br>
    <% end %>
    </div>
  </div>
</div>